name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installe cfn-lint
        run: pip install cfn-lint
      - name: Valide le pattern VPC Peering
        run: cfn-lint cloudformation/template-vpc-peering.yaml
      - name: Valide le pattern Transit Gateway
        run: cfn-lint cloudformation/template-transit-gateway.yaml
      - name: Valide le pattern VPC Endpoints
        run: cfn-lint cloudformation/template-vpc-endpoint.yaml
